cleanup git popd/dirs, combine _ws & _wdcode autocomplete

diff --git a/bin/git-popd b/bin/git-popd
--- a/bin/git-popd
+++ b/bin/git-popd
@@ -2,12 +2,12 @@
 
 # help
 if [[ $1 == "-h" || $1 == "--help" ]]; then
-cat <<EOF
+    cat <<EOF
 Usage: git-popd [-h|--help]
 
   -h, --help           Show this help message and exit
 EOF
-return 0
+    return 0
 fi
 
 # find repo root
@@ -16,23 +16,35 @@ repo_root=$(git rev-parse --show-toplevel 2>/dev/null) \
     || { echo "Not a git repository." >&2; return 1; }
 
 local stack_file="$repo_root/.ms-popd-stack"
-if [[ ! -s $stack_file ]]; then
-    echo "No branches in stack" >&2
-    return 1
-fi
-
-# read last entry
 local target_branch
-target_branch=$(tail -n 1 "$stack_file")
+if [[ ! -s $stack_file ]]; then
+    if git show-ref --quiet --verify refs/heads/master; then
+        target_branch='master'
+    elif git show-ref --quiet --verify refs/heads/main; then
+        target_branch='main'
+    else
+        echo "Error: neither 'master' nor 'main' branch exists" >&2
+        return 1
+    fi
 
-# remove last line
-local tmp_file
-tmp_file=$(mktemp) || { echo "Failed to create temp file." >&2; return 1; }
-sed '$d' "$stack_file" >| "$tmp_file"
-mv "$tmp_file" "$stack_file"
+    echo "No branches in stack, checking out ${target_branch}" >&2
+else
+    # read last entry
+    target_branch=$(tail -n 1 "$stack_file")
+
+    # remove last line
+    local tmp_file
+    tmp_file=$(mktemp) || { echo "Failed to create temp file." >&2; return 1; }
+    sed '$d' "$stack_file" >| "$tmp_file"
+    mv "$tmp_file" "$stack_file"
+fi
 
 # if now empty, delete it
 [[ ! -s $stack_file ]] && rm -f "$stack_file"
 
-# checkout
-git checkout "$target_branch"
+local current_branch=$(git rev-parse --abbrev-ref HEAD)
+if [[ "$current_branch" == "$target_branch" ]]; then
+    echo "✅ You are already on '$target_branch'"
+else
+    git checkout "${target_branch}"
+fi
